### ISSUE TITLE
Alert rule

### ISSUE THREAD

**Issue by itsjoke** [Cacti/plugin_syslog#31]
Hello,

This is my alert rule.
![alert_rule](https://user-images.githubusercontent.com/11266502/27626992-babb6694-5c1c-11e7-8a19-95c6ad6733b9.png)
***
This is my syslog setting.
![syslog_setting](https://user-images.githubusercontent.com/11266502/27627024-e474f40a-5c1c-11e7-90ad-f87e4bb0f541.png)
When the rule was triggered,I received the mail, but found the content was null.
pls help me what shoud I do?

tks,
David

**Comment by cigamit** [comment]
If you remove the alert command, which makes no sense by the way, does the alert work as expected?  The alert command should be something like '/bin/true' or something of that nature instead of what you have set, which would attempt to run a command like "localhost<br>..." which of course would fail.

Otherwise, it is working perfectly for me.  Next question, your syslog_incoming should include the following fields:

facility_id, priority_id, program, date, time, host, message, seq, status.  If you perform a SELECT * FROM syslog_incoming, are both the facility_id and priority_id > 0.  If not, you have to fix your template in the rsyslog.conf file.

Either way, your example above worked.  I'll keep this open for a few days.  If I don't hear back, I will close.

**Comment by itsjoke** [comment]
Hello
Thank you for reply.
I can receive the alert mail and the mail content was corrent when I change the ` HTML Based Email` to True.

![image](https://user-images.githubusercontent.com/11266502/27667133-47b2b546-5cab-11e7-8bcf-58cd126808e5.png)

**Comment by cigamit** [comment]
Interesting.

**Comment by netniV** [comment]
Is this still an issue? If so, it may well be that the text body isn't being properly set.

**Comment by David-yanp** [comment]
Yes, the issue still exists,
I can't find any setting to set the text body but `HTML Based Email` was normal.

**Comment by cigamit** [comment]
Should be resolved now.

**Comment by David-yanp** [comment]
It's work for me.
