### ISSUE TITLE
Feature request: Expand trigger condition logic.

### ISSUE THREAD

**Issue by smiles1969** [Cacti/plugin_syslog#9]
It would be very useful to add to the trigger logic and reference the SQL tables for the source host specific info.

For example:

If host_id = "blah" and message contains "blah" and host_template = "blah" then send alert

I see there is currently a SQL Expression string match type, but I am unsure of it's use and can not find any docs to explain it.

**Comment by cigamit** [comment]
It's actually pretty powerful:

SELECT * FROM syslog_incomming WHERE (mysql)

So, you can write:

hostname rlike '(abc|def|etc)' AND message rlike '(this|and|that)'

or even

There is a little problem joining the other tables.  It could be done, but it would be a left join, and on the hostname field in the host table, which might not be very efficient.  Look to line 288 in syslog_process.php

Here is a hint

SELECT * FROM syslog_incomming
LEFT JOIN host
ON host.hostname=syslog_incomming.hostname
LEFT JOIN host_template
ON host_template.id=host.host_template_id
WHERE ($message)

That should do it.  We would welcome a pull request.

Anything you want.  But remember there is a performance penalty.

**Comment by jpobeda** [comment]
I've tried something like:

message LIKE '%LINK-3-UPDOWN:%' AND host_id IN (29,28,26,30)

But it looks like querying 2 tables


```
10/Nov/2017 15:46:49 - DBCALL ERROR: SQL Assoc Failed!, Error: Unknown column 'host_id' in 'where clause'

10/Nov/2017 15:46:49 - DBCALL ERROR: SQL Assoc Failed!, Error:1054, SQL:'SELECT * FROM `syslog`.`syslog_incoming` WHERE (message LIKE '%LINK-3-UPDOWN:%' AND host_id IN (29,28,26,30)) AND status=108'
```
How can I make this query work? I'm using a separated db for syslog.

**Comment by cigamit** [comment]
Yea, the issue here is that there is no host_id column until the record is inserted into the main syslog table.  We can do a join, but it would be based upon the hostname.  In order for that to be efficient, we need to:

* Add index to host field in syslog_incoming table
* Add LEFT JOIN to the host table for the SQL Query type
* Your query would then be able to be AND host.id IN(1,2,3,4)

Do you want to take a crack at that?

**Comment by jpobeda** [comment]
Well thing is, there is nothing to compare against.

syslog_incoming has 'host' which is the hostname
syslog has host_id which is an id

Can't see the relation between these tables, I mean I do, but can't see how to relate them each other.

We'll need to add a column to either syslog or syslog_incoming, I'd say we need to add host to syslog table so we can compare s.host=si.host.

Does that make sense to you?

**Comment by jpobeda** [comment]
I removed my comment because it was creating more confusion and opened a new issue https://github.com/Cacti/plugin_syslog/issues/39

**Comment by jpobeda** [comment]
@smiles1969 ,

Can you edit your config.php file and change line 52
From
`$syslog_incoming_config['hostField']          = 'host_id';`

To
`$syslog_incoming_config['hostField']          = 'host';`

As far as I could see, $syslog_incoming_config['hostField'] it's only being used for the Alert rules and the Alert rules look at the syslog_incoming table and since there isn't a host_id column on that table it's been failing to execute the queries.

Once you change that you could create rules as follow
1.- Matching hostname
String Match Type = Hostname is
Syslog Message Match String=somehostname.com => at the moment the code looks for an exact match. It's easy enough to make it LIKE %something%.

2.- SQL Expression
The other rule you can create now, after that tiny change is
String Match Type = SQL Expression
Syslog Message Match String=message like '%SW_DAI-4-DHCP_SNOOPING_DENY%' AND host like '%someswitch-%'

These two rules now work for me.

If you can give it a go that'd be great. It's good to test on someone else installations as well

**Comment by snapbean25** [comment]
I also would like sort of this enhancement...Can the report function/search function query off the Program column...For ex. the Cicso ASA logs messages by ID type...searching in syslog doesnt work by querying that column..
Just a thought.
Thanks

**Comment by TheWitness** [comment]
This is resolved or will be in the next release.  Just finalizing things now.  Testing over the weekend God permitting.  The feature adds a "Level" attribute to the Alert.  The level can be host, for alerting/re-alerting at the host level.  The other option is System which alerts/re-alerts at the system level.

**Comment by TheWitness** [comment]
Next release requires Cacti 1.2.20 BTW.
